"""Type stubs for rsylla"""

from collections.abc import Iterator
from typing import Any

class ScyllaError(Exception):
    """Exception raised for ScyllaDB errors"""

    pass

class SessionBuilder:
    """Builder for creating ScyllaDB sessions with configuration"""

    def __init__(self) -> None: ...
    def known_node(self, hostname: str) -> SessionBuilder: ...
    def known_nodes(self, hostnames: list[str]) -> SessionBuilder: ...
    def use_keyspace(self, keyspace_name: str, case_sensitive: bool) -> SessionBuilder: ...
    def connection_timeout(self, duration_ms: int) -> SessionBuilder: ...
    def pool_size(self, size: int) -> SessionBuilder: ...
    def user(self, username: str, password: str) -> SessionBuilder: ...
    def compression(self, compression: str | None) -> SessionBuilder: ...
    def tcp_nodelay(self, nodelay: bool) -> SessionBuilder: ...
    def tcp_keepalive(self, keepalive_ms: int | None) -> SessionBuilder: ...
    def build(self) -> Session: ...

class Session:
    """ScyllaDB session for executing queries"""

    @staticmethod
    def connect(nodes: list[str]) -> Session: ...
    def execute(self, query: str, values: dict[str, Any] | None = None) -> QueryResult: ...
    def query(self, query: Query, values: dict[str, Any] | None = None) -> QueryResult: ...
    def prepare(self, query: str) -> PreparedStatement: ...
    def execute_prepared(
        self, prepared: PreparedStatement, values: dict[str, Any] | None = None
    ) -> QueryResult: ...
    def batch(self, batch: Batch, values: list[dict[str, Any]]) -> QueryResult: ...
    def use_keyspace(self, keyspace_name: str, case_sensitive: bool) -> None: ...
    def await_schema_agreement(self) -> bool: ...
    def get_cluster_data(self) -> str: ...
    def get_keyspace(self) -> str | None: ...

class Query:
    """CQL query with configuration options"""

    def __init__(self, query: str) -> None: ...
    def with_consistency(self, consistency: str) -> Query: ...
    def with_serial_consistency(self, serial_consistency: str) -> Query: ...
    def with_page_size(self, page_size: int) -> Query: ...
    def with_timestamp(self, timestamp: int) -> Query: ...
    def with_timeout(self, timeout_ms: int) -> Query: ...
    def with_tracing(self, tracing: bool) -> Query: ...
    def is_idempotent(self) -> bool: ...
    def set_idempotent(self, idempotent: bool) -> None: ...
    def get_contents(self) -> str: ...

class PreparedStatement:
    """Prepared CQL statement for efficient repeated execution"""

    def with_consistency(self, consistency: str) -> PreparedStatement: ...
    def with_serial_consistency(self, serial_consistency: str) -> PreparedStatement: ...
    def with_page_size(self, page_size: int) -> PreparedStatement: ...
    def with_timestamp(self, timestamp: int) -> PreparedStatement: ...
    def with_tracing(self, tracing: bool) -> PreparedStatement: ...
    def is_idempotent(self) -> bool: ...
    def set_idempotent(self, idempotent: bool) -> PreparedStatement: ...
    def get_id(self) -> bytes: ...
    def get_statement(self) -> str: ...

class QueryResult:
    """Result of a CQL query"""

    def rows(self) -> list[Row]: ...
    def first_row(self) -> Row | None: ...
    def single_row(self) -> Row: ...
    def first_row_typed(self) -> dict[str, Any] | None: ...
    def rows_typed(self) -> list[dict[str, Any]]: ...
    def col_specs(self) -> list[dict[str, Any]]: ...
    def tracing_id(self) -> str | None: ...
    def warnings(self) -> list[str]: ...
    def __iter__(self) -> Iterator[Row]: ...
    def __next__(self) -> Row: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...

class Row:
    """A row from a query result"""

    def columns(self) -> list[Any]: ...
    def as_dict(self) -> dict[str, Any]: ...
    def get(self, index: int) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __repr__(self) -> str: ...

class Batch:
    """Batch operation for executing multiple statements atomically"""

    def __init__(self, batch_type: str = "logged") -> None: ...
    def append_statement(self, query: str) -> None: ...
    def append_query(self, query: Query) -> None: ...
    def append_prepared(self, prepared: PreparedStatement) -> None: ...
    def with_consistency(self, consistency: str) -> Batch: ...
    def with_serial_consistency(self, serial_consistency: str) -> Batch: ...
    def with_timestamp(self, timestamp: int) -> Batch: ...
    def with_timeout(self, timeout_ms: int) -> Batch: ...
    def with_tracing(self, tracing: bool) -> Batch: ...
    def is_idempotent(self) -> bool: ...
    def set_idempotent(self, idempotent: bool) -> None: ...
    def statements_count(self) -> int: ...
    def __repr__(self) -> str: ...
